# Generated by Django 6.0.4 on 2026-04-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_company_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_status',
            field=models.CharField(choices=[('no', 'Нет'), ('yes', 'Да')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('admin', 'Администратор')], default='client', max_length=20),
        ),
    ]
