# Generated by Django 6.0.4 on 2026-04-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(editable=False, null=True, unique=True, verbose_name='ID пользователя'),
        ),
    ]
