# Generated by Django 6.0.4 on 2026-04-29 10:44

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_lead_tariff'),
        ('users', '0005_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_id', models.CharField(default=users.models.generate_accrual_id, editable=False, max_length=10, unique=True, verbose_name='ID начисления')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начисления')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_accruals', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='offers.lead', verbose_name='Лид')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accruals', to='offers.offer', verbose_name='Оффер')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_accruals', to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
                'ordering': ['-created_at'],
            },
        ),
    ]
