# Generated by Django 6.0.4 on 2026-05-03 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processing', 'В обработке'), ('paid', 'Выплачено'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработана')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Заявка на выплату',
                'verbose_name_plural': 'Заявки на выплату',
                'ordering': ['-created_at'],
            },
        ),
    ]
