# Generated by Django 6.0.4 on 2026-05-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrual',
            name='payout_status',
            field=models.CharField(choices=[('available', 'Доступно к выплате'), ('requested', 'Запрошено'), ('paid', 'Выплачено')], default='available', max_length=20, verbose_name='Статус выплаты'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='accruals',
            field=models.ManyToManyField(blank=True, related_name='withdrawal_requests', to='users.accrual', verbose_name='Начисления'),
        ),
    ]
