# Generated by Django 6.0.4 on 2026-05-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_accrual_payout_status_withdrawalrequest_accruals'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='Последние 4 цифры'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='card_mask',
            field=models.CharField(blank=True, max_length=30, verbose_name='Маска карты'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_system',
            field=models.CharField(blank=True, max_length=50, verbose_name='Платежная система'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Получатель'),
        ),
    ]
