# Generated by Django 6.0.4 on 2026-05-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_withdrawalrequest_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='card_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна карты'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип карты'),
        ),
    ]
