# Generated by Django 6.0.4 on 2026-05-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_withdrawalrequest_card_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Банк')),
                ('bin_prefix', models.CharField(max_length=8, unique=True, verbose_name='Первые цифры карты')),
                ('logo', models.FileField(blank=True, null=True, upload_to='bank_logos/', verbose_name='Логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'BIN банка',
                'verbose_name_plural': 'BIN банков',
                'ordering': ['bank_name', 'bin_prefix'],
            },
        ),
    ]
