# Generated by Django 6.0.4 on 2026-05-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_bankbin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbin',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к логотипу'),
        ),
    ]
