# Generated by Django 6.0.4 on 2026-05-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_bankbin_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='encrypted_card_number',
            field=models.TextField(blank=True, verbose_name='Зашифрованный номер карты'),
        ),
    ]
