# Generated by Django 6.0.4 on 2026-05-04 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_withdrawalrequest_encrypted_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_card_number', models.TextField(blank=True, verbose_name='Зашифрованный номер карты')),
                ('card_mask', models.CharField(blank=True, max_length=30, verbose_name='Маска карты')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Последние 4 цифры')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('payment_system', models.CharField(blank=True, max_length=50, verbose_name='Платёжная система')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Получатель')),
                ('card_type', models.CharField(blank=True, max_length=50, verbose_name='Тип карты')),
                ('card_country', models.CharField(blank=True, max_length=100, verbose_name='Страна карты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Платёжные реквизиты партнёра',
                'verbose_name_plural': 'Платёжные реквизиты партнёров',
            },
        ),
    ]
