# Generated by Django 6.0.4 on 2026-05-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_partnerpaymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpaymentdetails',
            name='bik',
            field=models.CharField(blank=True, max_length=9, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='partnerpaymentdetails',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AddField(
            model_name='partnerpaymentdetails',
            name='legal_bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное название банка'),
        ),
        migrations.AddField(
            model_name='partnerpaymentdetails',
            name='settlement_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bik',
            field=models.CharField(blank=True, max_length=9, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='legal_bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное название банка'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='settlement_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт'),
        ),
    ]
