# Generated by Django 6.0.4 on 2026-05-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_partnerpaymentdetails_bik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpaymentdetails',
            name='bank_inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='ИНН банка'),
        ),
        migrations.AddField(
            model_name='partnerpaymentdetails',
            name='bank_kpp',
            field=models.CharField(blank=True, max_length=9, verbose_name='КПП банка'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_inn',
            field=models.CharField(blank=True, max_length=10, verbose_name='ИНН банка'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_kpp',
            field=models.CharField(blank=True, max_length=9, verbose_name='КПП банка'),
        ),
    ]
