# Generated by Django 6.0.4 on 2026-05-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_partnerpaymentdetails_bank_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('partner', 'Партнер'), ('admin', 'Администратор')], default='client', max_length=20),
        ),
    ]
