# Generated by Django 6.0.4 on 2026-05-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_educationdocument_educationvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationvideo',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='education/previews/'),
        ),
        migrations.AlterField(
            model_name='educationvideo',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
