# Generated by Django 6.0.4 on 2026-05-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_educationvideo_preview_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
