# Generated by Django 6.0.4 on 2026-05-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_educationvideo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdocument',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
