# Generated by Django 6.0.4 on 2026-05-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_educationdocument_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('material_type', models.CharField(choices=[('video', 'Видео'), ('image', 'Изображение'), ('text', 'Текстовый материал')], max_length=20, verbose_name='Тип материала')),
                ('file', models.FileField(blank=True, null=True, upload_to='marketing_materials/', verbose_name='Файл')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Текстовый материал')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
