# Generated by Django 6.0.4 on 2026-05-18 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0021_delete_telegrammessage'),
        ('users', '0023_marketingmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmaterial',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_materials', to='offers.offer', verbose_name='Оффер'),
            preserve_default=False,
        ),
    ]
