# Generated by Django 6.0.4 on 2026-05-25 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_chattopic_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattopic',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_topics', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал тему'),
            preserve_default=False,
        ),
    ]
