# Generated by Django 6.0.4 on 2026-05-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_chattopic_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattopic',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], default='open', max_length=30, verbose_name='Статус'),
        ),
    ]
