# Generated by Django 6.0.4 on 2026-05-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='typing_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
