# Generated by Django 6.0.4 on 2026-05-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_typing_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chat/audio/', verbose_name='Аудиофайл'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('voice', 'Голосовое')], default='text', max_length=20, verbose_name='Тип сообщения'),
        ),
    ]
