# Generated by Django 6.0.4 on 2026-05-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_chatmessage_audio_file_chatmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='chat/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('voice', 'Голосовое'), ('image', 'Изображение')], default='text', max_length=20, verbose_name='Тип сообщения'),
        ),
    ]
