# Generated by Django 6.0.4 on 2026-05-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_chatmessage_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('voice', 'Голосовое'), ('image', 'Изображение'), ('file', 'Файл')], default='text', max_length=20, verbose_name='Тип сообщения'),
        ),
    ]
