# Generated by Django 6.0.4 on 2026-05-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_chatmessage_file_alter_chatmessage_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('voice', 'Голосовое'), ('image', 'Изображение'), ('file', 'Файл'), ('video_note', 'Видеокружок')], default='text', max_length=20, verbose_name='Тип сообщения'),
        ),
    ]
