# Generated by Django 6.0.4 on 2026-05-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_chatmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='video_note',
            field=models.FileField(blank=True, null=True, upload_to='chat/video_notes/'),
        ),
    ]
