# Generated by Django 6.0.4 on 2026-06-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_chatmessage_video_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн в чате'),
        ),
    ]
