# Generated by Django 6.0.4 on 2026-05-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение Telegram',
                'verbose_name_plural': 'Сообщения Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
