# Generated by Django 6.0.4 on 2026-05-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_portal', '0002_telegrammessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('last_update_id', models.BigIntegerField(default=0)),
            ],
        ),
    ]
