# Generated by Django 6.0.4 on 2026-04-12 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.BigIntegerField(editable=False, unique=True, verbose_name='ID оффера')),
                ('title', models.CharField(max_length=255, verbose_name='Название оффера')),
                ('description', models.TextField(blank=True, verbose_name='Описание оффера')),
                ('payout_type', models.CharField(choices=[('fixed', 'Фиксированная'), ('partner_status', 'По статусу партнера')], max_length=20, verbose_name='Форма выплаты')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вознаграждение')),
                ('activity_start', models.DateField(verbose_name='Начало активности оффера')),
                ('activity_end', models.DateField(verbose_name='Конец активности оффера')),
                ('landing_page', models.URLField(default='https://partnetix.ru', verbose_name='Посадочная страница')),
                ('promo_materials', models.FileField(blank=True, null=True, upload_to='promo_materials/', verbose_name='Промоматериалы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Текущий пользователь')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
                'ordering': ['-created_at'],
            },
        ),
    ]
