# Generated by Django 6.0.4 on 2026-04-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='payout_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная (₽)'), ('partner_status', 'По статусу партнера (%)')], default='fixed', max_length=20, verbose_name='Форма выплаты'),
        ),
    ]
