# Generated by Django 6.0.4 on 2026-04-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_payout_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='promo_materials',
        ),
        migrations.CreateModel(
            name='OfferPromoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='promo_materials/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_files', to='offers.offer', verbose_name='Оффер')),
            ],
            options={
                'verbose_name': 'Промоматериал',
                'verbose_name_plural': 'Промоматериалы',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
