# Generated by Django 6.0.4 on 2026-04-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_remove_offer_promo_materials_offerpromomaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма начислений'),
        ),
    ]
