# Generated by Django 6.0.4 on 2026-04-15 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer_total_earned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Регистрация завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='offers.offer', verbose_name='Оффер')),
                ('referral_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_visits', to=settings.AUTH_USER_MODEL, verbose_name='Кто пригласил')),
                ('visitor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_offers', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрированный пользователь')),
            ],
            options={
                'verbose_name': 'Переход по офферу',
                'verbose_name_plural': 'Переходы по офферам',
                'ordering': ['-created_at'],
            },
        ),
    ]
