# Generated by Django 6.0.4 on 2026-04-15 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_offervisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Статус')),
                ('reward_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вознаграждение (%)')),
            ],
            options={
                'verbose_name': 'Статус партнера',
                'verbose_name_plural': 'Статусы партнеров',
                'ordering': ['reward_percent'],
            },
        ),
        migrations.CreateModel(
            name='PartnerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('company', 'Юридическое лицо'), ('self_employed', 'Самозанятый')], max_length=20, verbose_name='Тип партнера')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('activity_type', models.CharField(blank=True, max_length=255, verbose_name='Вид деятельности')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('company_full_name', models.CharField(blank=True, max_length=255, verbose_name='Полное название организации')),
                ('company_short_name', models.CharField(blank=True, max_length=255, verbose_name='Сокращенное название организации')),
                ('postal_address', models.CharField(blank=True, max_length=255, verbose_name='Почтовый адрес')),
                ('legal_address', models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('contact_person_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО контактного лица')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_registrations', to='offers.offer', verbose_name='Оффер')),
                ('referral_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь по ссылке')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='offers.partnerstatus', verbose_name='Статус партнера')),
            ],
            options={
                'verbose_name': 'Регистрация партнера',
                'verbose_name_plural': 'Регистрации партнеров',
                'ordering': ['-created_at'],
            },
        ),
    ]
