# Generated by Django 6.0.4 on 2026-04-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_partnerregistration_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='stats_reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сброса статистики'),
        ),
    ]
