# Generated by Django 6.0.4 on 2026-04-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_partnerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerregistration',
            name='is_active_partner',
            field=models.BooleanField(default=True, verbose_name='Активный партнер'),
        ),
    ]
