# Generated by Django 6.0.4 on 2026-04-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_partnerregistration_is_active_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerregistration',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='leads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лидов'),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма вознаграждения'),
        ),
    ]
