# Generated by Django 6.0.4 on 2026-04-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_partnerregistration_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerregistration',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Оффер по умолчанию'),
        ),
    ]
