# Generated by Django 6.0.4 on 2026-04-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_partnerregistration_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Оффер по умолчанию'),
        ),
    ]
