# Generated by Django 6.0.4 on 2026-04-27 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_offer_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый лид', max_length=255, verbose_name='Название лида')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма сделки')),
                ('partner_reward', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Вознаграждение партнера')),
                ('status', models.CharField(choices=[('new', 'Новый лид'), ('in_progress', 'В работе'), ('cancelled', 'Отменен'), ('deal', 'Сделка')], default='new', max_length=20, verbose_name='Статус лида')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_leads', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='offers.offer', verbose_name='Оффер')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
    ]
