# Generated by Django 6.0.4 on 2026-04-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('period', models.CharField(choices=[('monthly', 'Месячный тариф'), ('yearly', 'Годовой тариф')], max_length=20, verbose_name='Период')),
                ('leads_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит лидов')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('trial_days', models.PositiveIntegerField(default=0, verbose_name='Бесплатный период, дней')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['period', 'price'],
            },
        ),
    ]
