# Generated by Django 6.0.4 on 2026-04-28 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_lead_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='offers.tariff', verbose_name='Тарифный план'),
        ),
    ]
