# Generated by Django 6.0.4 on 2026-04-30 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_lead_partner_link_offervisit_partner_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offervisit',
            name='partner_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='offers.partnerlink', verbose_name='Партнерская ссылка'),
        ),
    ]
