# Generated by Django 6.0.4 on 2026-05-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_telegrammessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramMessage',
        ),
    ]
