# Generated by Django 6.0.4 on 2026-06-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0021_delete_telegrammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerregistration',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='partner_registrations_many', to='offers.offer', verbose_name='Офферы'),
        ),
    ]
